INSERT INTO EXCHANGE_RATES (PROVIDED_CURRENCY, EXCHANGE_CURRENCY,EXCHANGE_RATE) VALUES ('INR','EUR',80.74);
INSERT INTO EXCHANGE_RATES (PROVIDED_CURRENCY, EXCHANGE_CURRENCY,EXCHANGE_RATE) VALUES ('INR','AUD',54.43);
INSERT INTO EXCHANGE_RATES (PROVIDED_CURRENCY, EXCHANGE_CURRENCY,EXCHANGE_RATE) VALUES ('INR','USD',79.29);
INSERT INTO EXCHANGE_RATES (PROVIDED_CURRENCY, EXCHANGE_CURRENCY,EXCHANGE_RATE) VALUES ('INR','SEK',7.56);
INSERT INTO EXCHANGE_RATES (PROVIDED_CURRENCY, EXCHANGE_CURRENCY,EXCHANGE_RATE) VALUES ('INR','KWD',257.88);